MedicalOffice/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MedicalOffice.Models
{
    public class Doctor
    {
        public Doctor()
        {
            this.Patients = new HashSet<Patient>();
            DoctorSpecialties = new HashSet<DoctorSpecialty>();
        }

        public int ID { get; set; }

        [Display(Name = "Doctor")]
        public string FullName
        {
            get
            {
                return "Dr. " + FirstName
                    + (string.IsNullOrEmpty(MiddleName) ? " " :
                        (" " + (char?)MiddleName[0] + ". ").ToUpper())
                    + LastName;
            }
        }

        public string FormalName
        {
            get
            {
                return LastName + ", " + FirstName
                    + (string.IsNullOrEmpty(MiddleName) ? "" :
                        (" " + (char?)MiddleName[0] + ".").ToUpper());
            }
        }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "You cannot leave the first name blank.")]
        [StringLength(50, ErrorMessage = "First name cannot be more than 50 characters long.")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        [StringLength(50, ErrorMessage = "Middle name cannot be more than 50 characters long.")]
        public string MiddleName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "You cannot leave the last name blank.")]
        [StringLength(100, ErrorMessage = "Last name cannot be more than 100 characters long.")]
        public string LastName { get; set; }

        public virtual DoctorPhysicalDescription DoctorPhysicalDescription { get; set; }

        public virtual ICollection<Patient> Patients { get; set; }

        [Display(Name = "Specialties")]
        public ICollection<DoctorSpecialty> DoctorSpecialties { get; set; }
    }
}

MedicalOffice/Controllers/DoctorPhysicalDescriptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicalOffice.Data;
using MedicalOffice.Models;

namespace MedicalOffice.Controllers
{
    public class DoctorPhysicalDescriptionsController : Controller
    {
        private readonly MedicalOfficeContext _context;

        public DoctorPhysicalDescriptionsController(MedicalOfficeContext context)
        {
            _context = context;
        }

        // GET: DoctorPhysicalDescriptions
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Doctors");
        }

        // GET: DoctorPhysicalDescriptions/Create
        public IActionResult Add(int? DoctorID, string DoctorName)
        {
            if (!DoctorID.HasValue)
            {
                return RedirectToAction("Index", "Doctors");
            }
            ViewData["DoctorName"] = DoctorName;
            DoctorPhysicalDescription d = new DoctorPhysicalDescription()
            {
                DoctorID = DoctorID.GetValueOrDefault()
            };
            return View(d);
        }

        // POST: DoctorPhysicalDescriptions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("DoctorID,Height,Weight,HairColour,IdentifyingMarks")] DoctorPhysicalDescription doctorPhysicalDescription, string DoctorName)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(doctorPhysicalDescription);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details","Doctors", new { id=doctorPhysicalDescription.DoctorID });
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            ViewData["DoctorName"] = DoctorName;
            return View(doctorPhysicalDescription);
        }

        // GET: DoctorPhysicalDescriptions/Edit/5
        public async Task<IActionResult> Update(int? id, string DoctorName)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctorPhysicalDescription = await _context.DoctorPhysicalDescriptions.FindAsync(id);
            if (doctorPhysicalDescription == null)
            {
                return NotFound();
            }
            ViewData["DoctorName"] = DoctorName;
            return View(doctorPhysicalDescription);
        }

        // POST: DoctorPhysicalDescriptions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("DoctorID,Height,Weight,HairColour,IdentifyingMarks")] DoctorPhysicalDescription doctorPhysicalDescription, string DoctorName)
        {
            if (id != doctorPhysicalDescription.DoctorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doctorPhysicalDescription);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", "Doctors", new { id = doctorPhysicalDescription.DoctorID });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorPhysicalDescriptionExists(doctorPhysicalDescription.DoctorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewData["DoctorName"] = DoctorName;
            return View(doctorPhysicalDescription);
        }

        private bool DoctorPhysicalDescriptionExists(int id)
        {
            return _context.DoctorPhysicalDescriptions.Any(e => e.DoctorID == id);
        }
    }
}

MedicalOffice/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicalOffice.Data;
using MedicalOffice.Models;
using MedicalOffice.ViewModels;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.AspNetCore.Authorization;
using MedicalOffice.Utilities;

namespace MedicalOffice.Controllers
{
    [Authorize(Roles ="Admin,Supervisor")]
    public class DoctorsController : Controller
    {
        private readonly MedicalOfficeContext _context;

        public DoctorsController(MedicalOfficeContext context)
        {
            _context = context;
        }

        // GET: Doctors
        public async Task<IActionResult> Index(int? page, int? pageSizeID)
        {
            var doctors = from d in _context.Doctors
                .Include(d => d.DoctorSpecialties).ThenInclude(d => d.Specialty)
                          select d;
            //Handle Paging
            int pageSize;//This is the value we will pass to PaginatedList
            if (pageSizeID.HasValue)
            {
                //Value selected from DDL so use and save it to Cookie
                pageSize = pageSizeID.GetValueOrDefault();
                CookieHelper.CookieSet(HttpContext, "pageSizeValue", pageSize.ToString(), 30);
            }
            else
            {
                //Not selected so see if it is in Cookie
                pageSize = Convert.ToInt32(HttpContext.Request.Cookies["pageSizeValue"]);
            }
            pageSize = (pageSize == 0) ? 2 : pageSize;//Neither Selected or in Cookie so go with default
            ViewData["pageSizeID"] =
                new SelectList(new[] { "2", "5", "10", "20", "30", "40", "50", "100", "500" }, pageSize.ToString());
            var pagedData = await PaginatedList<Doctor>.CreateAsync(doctors.AsNoTracking(), page ?? 1, pageSize);
            return View(pagedData);
        }

        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors.Include(d=>d.Patients)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            Doctor doctor = new Doctor();
            PopulateAssignedSpecialtyData(doctor);
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,MiddleName,LastName")] Doctor doctor, string[] selectedOptions)
        {
            try
            {
                UpdateDoctorSpecialties(selectedOptions, doctor);
                if (ModelState.IsValid)
                {
                    _context.Add(doctor);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Something went wrong in the database.");
            }
            PopulateAssignedSpecialtyData(doctor);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
               .Include(d => d.DoctorSpecialties).ThenInclude(d => d.Specialty)
               .AsNoTracking()
               .SingleOrDefaultAsync(d => d.ID == id);

            if (doctor == null)
            {
                return NotFound();
            }
            PopulateAssignedSpecialtyData(doctor);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string[] selectedOptions)
        {
            //Get the object from the database
            var doctorToUpdate = await _context.Doctors
                .Include(d => d.DoctorSpecialties).ThenInclude(d => d.Specialty)
                .SingleOrDefaultAsync(d => d.ID == id);
            if (doctorToUpdate==null)
            {
                return NotFound();
            }

            //Update the Doctor's Specialties
            UpdateDoctorSpecialties(selectedOptions, doctorToUpdate);


            //Try updating it wiht the posted values
            if (await TryUpdateModelAsync<Doctor>(doctorToUpdate, "",
                d=>d.FirstName, d => d.MiddleName, d => d.LastName))
            {
                try
                {
                    _context.Update(doctorToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctorToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Something went wrong in the database.");
                }
                return RedirectToAction(nameof(Index));
            }
            //Validaiton Error so give the user another chance.
            PopulateAssignedSpecialtyData(doctorToUpdate);
            return View(doctorToUpdate);
        }

        // GET: Doctors/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctor = await _context.Doctors.FindAsync(id);
            try
            {
                _context.Doctors.Remove(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException dex)
            {
                if (dex.InnerException.Message.Contains("FK_Patients_Doctors_DoctorID"))
                {
                    ModelState.AddModelError("", "Unable to save changes. Remember, you cannot delete a Doctor that has Patients.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(doctor);

        }

        public PartialViewResult ListOfSpecialtiesDetails(int id)
        {
            var query = from s in _context.DoctorSpecialties.Include(p => p.Specialty)
                        where s.DoctorID == id
                        select s;
            return PartialView("_ListOfSpecialities", query.ToList());
        }

        public PartialViewResult ListOfPatientsDetails(int id)
        {
            var query = from s in _context.Patients
                        where s.DoctorID == id
                        select s;
            return PartialView("_ListOfPatients", query.ToList());
        }
        public PartialViewResult DoctorPD(int id)
        {
            //Now get the MASTER record, the Doctor, so it can be displayed at the top of the screen
            Doctor doctor = _context.Doctors
                .Where(p => p.ID == id).FirstOrDefault();
            ViewBag.Doctor = doctor;
            var query = from d in _context.DoctorPhysicalDescriptions
                        where d.DoctorID == id
                        select d;
            return PartialView("_DoctorPhysicalDescription", query.FirstOrDefault());
        }
                
        private void PopulateAssignedSpecialtyData(Doctor doctor)
        {
            var allSpecialties = _context.Specialties;
            var docSpecialties = new HashSet<int>(doctor.DoctorSpecialties.Select(b => b.SpecialtyID));
            var selected = new List<OptionVM>();

MedicalOffice/Views/Doctors/Create.cshtml
@model MedicalOffice.Models.Doctor

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Doctor</h4>
<hr />
<form asp-action="Create">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label"> Specialties Accredited</label> <button type="button" id="btnRight" class="btn btn-danger btn-sm">
                        <strong>-</strong>
                    </button>
                    @Html.ListBox("selectedOptions", (MultiSelectList)ViewBag.selOpts, new { @size = 10, @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    <label class="control-label"> Choose Specialties</label> <button type="button" id="btnLeft" class="btn btn-success btn-sm">
                        <strong>+</strong>
                    </button>
                    @Html.ListBox("availOptions", (MultiSelectList)ViewBag.availOpts, new { @size = 10, @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <input type="submit" id="btnSubmit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/multiselect.js"></script>
}

MedicalOffice/Views/Doctors/Delete.cshtml
@model MedicalOffice.Models.Doctor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MedicalOffice/Views/Doctors/Details.cshtml
@model MedicalOffice.Models.Doctor

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>
<div>
    <h4>Doctor: @Model.FullName</h4>
    <hr />
</div>
<div>

    <!-- Nav tabs -->
    <ul class="nav nav-pills" id="myTabs" role="tablist">
        <li class="nav-item">
            <a href="#basic" aria-controls="basic" role="tab" class="nav-link active" name="basic" data-toggle="tab" aria-selected="false">Basic Details</a>
        </li>
        <li class="nav-item">
            <a href="#patients" aria-controls="patients" role="tab" class="nav-link" name="patients" data-toggle="tab" aria-selected="false">Patients</a>
        </li>
        <li class="nav-item">
            <a href="#specialities" aria-controls="specialities" role="tab" class="nav-link" name="specialities" data-toggle="tab" aria-selected="false">Specialities</a>
        </li>
        <li class="nav-item">
            <a href="#physical" aria-controls="physical" role="tab" class="nav-link" name="physical" data-toggle="tab" aria-selected="false">Physical Description</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade ml-3 show active" id="basic">
            <br />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.MiddleName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.MiddleName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.LastName)
                </dd>
            </dl>
        </div>
        <div role="tabpanel" class="tab-pane fade ml-3" id="patients" aria-labelledby="patients-tab">
            <br />
        </div>
        <div role="tabpanel" class="tab-pane fade ml-3" id="specialities" aria-labelledby="specialities-tab">
            <br />
        </div>
        <div role="tabpanel" class="tab-pane fade ml-3" id="physical" aria-labelledby="physical-tab">
            <br />
        </div>
    </div>
</div>
<hr />
<br />
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit Doctor</a> |
    <a asp-action="Index">Back to Doctor List</a>
</div>
@section Scripts {
    <script type="text/javascript">
            $('.nav-link').click(function () {
                var activeTab = $(this).attr("name");
                switch (activeTab) {
                    case 'patients':$('#patients').load('/Doctors/ListOfPatientsDetails/@Model.ID');
                        break;
                    case 'specialities': $('#specialities').load('/Doctors/ListOfSpecialtiesDetails/@Model.ID');
                        break;
                    case 'physical': $('#physical').load('/Doctors/DoctorPD/@Model.ID');
                        break;
                    default: break;
                };
            })
    </script>
}


MedicalOffice/Views/Doctors/Edit.cshtml
@model MedicalOffice.Models.Doctor

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Doctor</h4>
<hr />

<form asp-action="Edit">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label"> Specialties Accredited</label> <button type="button" id="btnRight" class="btn btn-danger btn-sm">
                        <strong>-</strong>
                    </button>
                    @Html.ListBox("selectedOptions", (MultiSelectList)ViewBag.selOpts, new { @size = 10, @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    <label class="control-label"> Choose Specialties</label> <button type="button" id="btnLeft" class="btn btn-success btn-sm">
                        <strong>+</strong>
                    </button>
                    @Html.ListBox("availOptions", (MultiSelectList)ViewBag.availOpts, new { @size = 10, @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input type="submit" id="btnSubmit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/multiselect.js"></script>
}

MedicalOffice/Views/Doctors/Index.cshtml
@model IEnumerable<MedicalOffice.Models.Doctor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-action="Index">
    <table class="table">
        <colgroup>
            <col span="1" />
            <col width="300" , span="1" />
            <col span="1" />
        </colgroup>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FullName)
                </th>
                <th>
                    Specialties
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @{
                            int specCount = item.DoctorSpecialties.Count;
                            if (specCount > 0)
                            {
                                string firstSpec = item.DoctorSpecialties.FirstOrDefault().Specialty.SpecialtyName;
                                if (specCount > 1)
                                {
                                    string specList = "";
                                    var c = item.DoctorSpecialties.ToList();
                                    for (int i = 1; i < specCount; i++)
                                    {
                                        specList += c[i].Specialty.SpecialtyName + " <br />";
                                    }
                                    <a class="" role="button" data-toggle="collapse" href="#collapseSum@(item.ID)" aria-expanded="false" aria-controls="collapseSum@(item.ID)">
                                        @firstSpec... <span class="badge badge-info">@specCount</span>
                                    </a>
                                    <div class="collapse" id="collapseSum@(item.ID)">
                                        @Html.Raw(specList)
                                    </div>
                                }
                                else
                                {
                                    @firstSpec
                                }
                            }
                        }
                        @*For help with Bootstrap Collapse see: https://getbootstrap.com/docs/4.0/components/collapse/*@
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                        @if (User.IsInRole("Admin"))
                        {
                            @:|
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <partial name="_PagingNavBar" />
</form>

MedicalOffice/Views/Doctors/_DoctorPhysicalDescription.cshtml
@model MedicalOffice.Models.DoctorPhysicalDescription
@{
    MedicalOffice.Models.Doctor doctor = (MedicalOffice.Models.Doctor)ViewBag.Doctor;
}
@if (Model?.DoctorID > 0)
{
    <div>
        <h4>Physical Description</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Height)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Height)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Weight)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Weight)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.HairColour)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.HairColour)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.IdentifyingMarks)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IdentifyingMarks)
            </dd>
        </dl>
        <div class="ml-4">
            <a asp-controller="DoctorPhysicalDescriptions" asp-action="Update" asp-route-ID="@Model.DoctorID" asp-route-DoctorName="@doctor.FullName" >
                <span class="btn btn-primary"><strong>&#x270D; Update</strong></span>
            </a>
        </div>
    </div>
}
else
{
    <p>
        No Physical Description Entered.
    </p>
    <div class="ml-4">
        <a asp-controller="DoctorPhysicalDescriptions" asp-action="Add" asp-route-DoctorID="@doctor.ID" asp-route-DoctorName="@doctor.FullName">
            <span class="btn btn-success"><strong>&#x271A; Add</strong></span>
        </a>
    </div>
}
