MedicalOffice/Controllers/PatientApptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicalOffice.Data;
using MedicalOffice.Models;
using MedicalOffice.Utilities;
using Microsoft.AspNetCore.Authorization;

[Authorize]
public class PatientApptController : Controller
{
    private readonly MedicalOfficeContext _context;

    public PatientApptController(MedicalOfficeContext context)
    {
        _context = context;
    }

    // GET: Appointments
    public async Task<IActionResult> Index(int? PatientID, int? page, int? pageSizeID, int? ApptReasonID, string actionButton,
        string SearchString, string sortDirection = "desc", string sortField = "Appointment")
    {
        if (!PatientID.HasValue)
        {
            //Can't work without a patient so go back to Patient Index
            return RedirectToAction("Index", "Patients");
        }
        PopulateDropDownLists();
        ViewData["Filtering"] = "btn-outline-secondary";//Instead of keeping the filter open, change colour of button

        var appts = from a in _context.Appointments
                    .Include(a => a.ApptReason)
                    .Include(a => a.Patient)
                    where a.PatientID == PatientID.GetValueOrDefault()
                    select a;

        if (ApptReasonID.HasValue)
        {
            appts = appts.Where(p => p.ApptReasonID == ApptReasonID);
            ViewData["Filtering"] = "btn-danger";
        }
        if (!String.IsNullOrEmpty(SearchString))
        {
            appts = appts.Where(p => p.Notes.ToUpper().Contains(SearchString.ToUpper()));
            ViewData["Filtering"] = "btn-danger";
        }
        //Before we sort, see if we have called for a change of filtering or sorting
        if (!String.IsNullOrEmpty(actionButton)) //Form Submitted so lets sort!
        {
            page = 1;//Reset back to first page when sorting or filtering

            if (actionButton != "Filter")//Change of sort is requested
            {
                if (actionButton == sortField) //Reverse order on same field
                {
                    sortDirection = sortDirection == "asc" ? "desc" : "asc";
                }
                sortField = actionButton;//Sort by the button clicked
            }
        }
        //Now we know which field and direction to sort by
        if (sortField == "Extra Fees")//Sorting by Patient Name
        {
            if (sortDirection == "asc")
            {
                appts = appts
                    .OrderBy(p => p.extraFee);
            }
            else
            {
                appts = appts
                    .OrderByDescending(p => p.extraFee);
            }
        }
        else if (sortField.Contains("Reason"))
        {
            if (sortDirection == "asc")
            {
                appts = appts
                    .OrderBy(p => p.ApptReason.ReasonName);
            }
            else
            {
                appts = appts
                    .OrderByDescending(p => p.ApptReason.ReasonName);
            }
        }
        else //Date
        {
            if (sortDirection == "asc")
            {
                appts = appts
                    .OrderByDescending(p => p.appDate);
            }
            else
            {
                appts = appts
                    .OrderBy(p => p.appDate);
            }
        }
        //Set sort for next time
        ViewData["sortField"] = sortField;
        ViewData["sortDirection"] = sortDirection;

        //Now get the MASTER record, the patient, so it can be displayed at the top of the screen
        Patient patient = _context.Patients
            .Include(p => p.Doctor)
            .Include(p => p.PatientConditions)
            .ThenInclude(pc => pc.Condition)
            .Where(p => p.ID == PatientID.GetValueOrDefault()).FirstOrDefault();
        ViewBag.Patient = patient;

        //Handle Paging
        int pageSize;//This is the value we will pass to PaginatedList
        if (pageSizeID.HasValue)
        {
            //Value selected from DDL so use and save it to Cookie
            pageSize = pageSizeID.GetValueOrDefault();
            CookieHelper.CookieSet(HttpContext, "pageSizeValue", pageSize.ToString(), 30);
        }
        else
        {
            //Not selected so see if it is in Cookie
            pageSize = Convert.ToInt32(HttpContext.Request.Cookies["pageSizeValue"]);
        }
        pageSize = (pageSize == 0) ? 2 : pageSize;//Neither Selected or in Cookie so go with default
        ViewData["pageSizeID"] =
            new SelectList(new[] { "2", "5", "10", "20", "30", "40", "50", "100", "500" }, pageSize.ToString());
        var pagedData = await PaginatedList<Appointment>.CreateAsync(appts.AsNoTracking(), page ?? 1, pageSize);
        return View(pagedData);
    }

    // GET: PatientAppt/Add
    public IActionResult Add(int? PatientID, string PatientName)
    {
        if (!PatientID.HasValue)
        {
            return RedirectToAction("Index", "Patients");
        }
        ViewData["PatientName"] = PatientName;
        Appointment a = new Appointment()
        {
            PatientID = PatientID.GetValueOrDefault()
        };
        PopulateDropDownLists();
        return View(a);
    }

    // POST: PatientAppt/Add
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Add([Bind("ID,Notes,appDate,PatientID,extraFee,ApptReasonID")] Appointment appointment, string PatientName)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { appointment.PatientID });
            }
        }
        catch (DbUpdateException)
        {
            ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
        }
        PopulateDropDownLists(appointment);
        ViewData["PatientName"] = PatientName;
        return View(appointment);
    }

    // GET: PatientAppt/Edit/5
    public async Task<IActionResult> Update(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var appointment = await _context.Appointments
            .Include(a => a.ApptReason)
            .Include(a => a.Patient)
            .FirstOrDefaultAsync(m => m.ID == id);
        if (appointment == null)
        {
            return NotFound();
        }
        PopulateDropDownLists(appointment);
        return View(appointment);
    }

    // POST: PatientAppt/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(int id)
    {
        var appointmentToUpdate = await _context.Appointments
            .Include(a => a.ApptReason)
            .Include(a => a.Patient)
            .FirstOrDefaultAsync(m => m.ID == id);
        //Check that you got it or exit with a not found error
        if (appointmentToUpdate == null)
        {
            return NotFound();
        }

        //Try updating it with the values posted
        if (await TryUpdateModelAsync<Appointment>(appointmentToUpdate, "",
            p => p.Notes, p => p.appDate, p => p.extraFee, p => p.ApptReasonID))
        {
            try
            {
                _context.Update(appointmentToUpdate);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { appointmentToUpdate.PatientID });
            }

            catch (DbUpdateConcurrencyException)
            {
                if (!AppointmentExists(appointmentToUpdate.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
        }
        PopulateDropDownLists(appointmentToUpdate);
        return View(appointmentToUpdate);
    }

    // GET: PatientAppt/Delete/5
    public async Task<IActionResult> Remove(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var appointment = await _context.Appointments
            .Include(a => a.ApptReason)
            .Include(a => a.Patient)
            .FirstOrDefaultAsync(m => m.ID == id);
        if (appointment == null)
        {
            return NotFound();
        }
        return View(appointment);
    }

    // POST: PatientAppt/Delete/5
    [HttpPost, ActionName("Remove")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RemoveConfirmed(int id)
    {
        var appointment = await _context.Appointments
            .Include(a => a.ApptReason)
            .Include(a => a.Patient)
            .FirstOrDefaultAsync(m => m.ID == id);

        try
        {
            _context.Appointments.Remove(appointment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { appointment.PatientID });
        }
        catch (Exception)
        {

MedicalOffice/Views/PatientAppt/Add.cshtml
@model MedicalOffice.Models.Appointment

@{
    ViewData["Title"] = "Add Appointment";
}


<h2>Add Appointment for Patient: @ViewData["PatientName"]</h2>
<hr />
<form asp-action="Add">
    <input type="hidden" name="PatientID" value="@Model.PatientID" />
    <input type="hidden" name="PatientName" value="@ViewData["PatientName"]" />
    <div class="row">
        <div class="col-md-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="appDate" class="control-label"></label>
                    <input asp-for="appDate" class="form-control" />
                    <span asp-validation-for="appDate" class="text-danger"></span>
                </div>
                <label asp-for="Notes" class="control-label"></label>
                <textarea asp-for="Notes" rows="5" cols="40" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="extraFee" class="control-label"></label>
                <input asp-for="extraFee" class="form-control" />
                <span asp-validation-for="extraFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApptReasonID" class="control-label"></label>
                <select asp-for="ApptReasonID" class="form-control" asp-items="ViewBag.ApptReasonID">
                    <option value="">No Reason Given</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </div>
    </div>
</form>
<div>
    <a asp-action="Index" asp-controller="PatientAppt" asp-route-PatientID="@Model.PatientID">Back to Patient</a>
</div>

MedicalOffice/Views/PatientAppt/Index.cshtml
@model IEnumerable<MedicalOffice.Models.Appointment>

@{
    ViewData["Title"] = "Patient Appointments";
    MedicalOffice.Models.Patient patient = (MedicalOffice.Models.Patient)ViewBag.Patient;
}
<p> </p>
<div class="media">
    <div>
        @{
            if (patient.imageContent != null && patient.imageMimeType.Contains("image"))
            {
                string imageBase64 = Convert.ToBase64String(patient.imageContent);
                string imageSrc = string.Format("data:" + patient.imageMimeType + ";base64,{0}", imageBase64);
                <img src="@imageSrc" alt="Profile Picture of @patient.FullName" title="Profile Picture of @patient.FullName"
                     style="max-width: 150px; max-height: 150px" class="img-fluid rounded" />
            }
            else
            {
                <img src="~/pictures/blankProfile.jpg" style="max-width: 150px; max-height: 150px" class="img-responsive img-rounded" />
            }
        }
    </div>
    <div class="media-body ml-3">
        <h2><text class="hidden-xs">Patient: </text>@patient.FullName</h2>
        <div class="row">
            <div class="col-md-6">
                <dl class="row">
                    <dt class="col-md-4">
                        @Html.DisplayNameFor(model => patient.OHIP)
                    </dt>
                    <dd class="col-md-8">
                        @Html.DisplayFor(model => patient.OHIP)
                    </dd>
                    <dt class="col-md-4">
                        @Html.DisplayNameFor(model => patient.LastName)
                    </dt>
                    <dd class="col-md-8">
                        @Html.DisplayFor(model => patient.LastName)
                    </dd>
                    <dt class="col-md-4">
                        First/Middle
                    </dt>
                    <dd class="col-md-8">
                        @Html.DisplayFor(model => patient.FirstName) @Html.DisplayFor(model => patient.MiddleName)
                    </dd>
                    <dt class="col-md-4">
                        Age (@Html.DisplayNameFor(model => patient.DOB))
                    </dt>
                    <dd class="col-md-8">
                        @patient.Age (@Html.DisplayFor(model => patient.DOB))
                    </dd>
                    <dt class="col-md-4">
                        @Html.DisplayNameFor(model => patient.ExpYrVisits)
                    </dt>
                    <dd class="col-md-8">
                        @Html.DisplayFor(model => patient.ExpYrVisits)
                    </dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="row">
                    <dt class="col-md-3">
                        @Html.DisplayNameFor(model => patient.Phone)
                    </dt>
                    <dd class="col-md-9">
                        @Html.DisplayFor(model => patient.Phone)
                    </dd>
                    <dt class="col-md-3">
                        @Html.DisplayNameFor(model => patient.eMail)
                    </dt>
                    <dd class="col-md-9">
                        @Html.DisplayFor(model => patient.eMail)
                    </dd>
                    <dt class="col-md-3">
                        @Html.DisplayNameFor(model => patient.Doctor)
                    </dt>
                    <dd class="col-md-9">
                        @Html.DisplayFor(model => patient.Doctor.FullName)
                    </dd>
                    <dt class="col-md-3">
                        @Html.DisplayNameFor(model => patient.MedicalTrial)
                    </dt>
                    <dd class="col-md-9">
                        @Html.DisplayFor(model => patient.MedicalTrial.TrialName)
                    </dd>
                    <dt class="col-sm-3">
                        @Html.DisplayNameFor(model => patient.PatientConditions)
                    </dt>
                    <dd class="col-sm-9">
                        @{
                            int condCount = patient.PatientConditions.Count;
                            if (condCount > 0)
                            {
                                string firstCond = patient.PatientConditions.FirstOrDefault().Condition.ConditionName;
                                if (condCount > 1)
                                {
                                    string condList = firstCond;
                                    var c = patient.PatientConditions.ToList();
                                    for (int i = 1; i < condCount; i++)
                                    {
                                        condList += ", " + c[i].Condition.ConditionName;
                                    }
                                    <a tabindex="0" class="" role="button" data-toggle="popover"
                                       data-trigger="focus" title="Conditions" data-placement="bottom" data-content="@condList">@firstCond...<span class="badge">@condCount</span></a>
                                }
                                else
                                {
                                    @firstCond
                                }
                            }
                        }
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<form asp-action="Index">
    <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
    <input type="hidden" name="sortField" value="@ViewData["sortField"]" />
    <input type="hidden" name="PatientID" value="@patient.ID" />

    <dl class="dl-horizontal">
        <dt>
            <button class="btn @(ViewData["Filtering"])" type="button" data-toggle="collapse" id="filterToggle" data-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
                Filter
            </button>
        </dt>
        <dd>
            <div class="form-horizontal">
                <div class="collapse card card-body bg-light" style="padding-top: 10px; padding-bottom: 0px;" id="collapseFilter">
                    <div class="form-row">
                        <div class="form-group col-md-4 ml-md-3">
                            <label class="control-label">Reason:</label>
                            @Html.DropDownList("ApptReasonID", null, "All Reasons", htmlAttributes: new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-4">
                            <label class="control-label">Search Notes:</label>
                            @Html.TextBox("SearchString", null, new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3 align-self-end">
                            <input type="submit" name="actionButton" value="Apply" class="btn btn-primary" />
                            <a asp-action="Index" asp-route-PatientID="@patient.ID">Clear</a>
                        </div>
                    </div>
                </div>
            </div>
        </dd>
        <dt>
        </dt>
        <dd>
            <div>
                <table class="table">
                    <colgroup>
                        <col span="1" />
                        <col span="1" />
                        <col span="1" />
                        <col span="1" width="400" />
                        <col span="1" />
                    </colgroup>
                    <tr>
                        <th>
                            <input type="submit" name="actionButton" value="Appointment" class="btn btn-link" />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Appt. Reason" class="btn btn-link" />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Extra Fees" class="btn btn-link" />
                            @{decimal totalFees = 0m; }
                        </th>
                        <th>
                            <input type="submit" disabled="disabled" value="Notes" class="btn btn-link" />
                        </th>
                        <th>
                            <a asp-controller="PatientAppt" asp-action="Add" asp-route-PatientID="@patient.ID" asp-route-PatientName="@patient.FullName">
                                <span class="btn btn-success"><strong>&#x271A; Add</strong></span>
                            </a>
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.appDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ApptReason.ReasonName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.extraFee)
                                @{ totalFees += item.extraFee;}
                            </td>
                            <td>
                                @{
                                    string[] noteWords = item.Notes.Split(' ');
                                    if (noteWords.Count() > 7)
                                    {
                                        <a class="" role="button" data-toggle="collapse" href="#collapseSum@(item.ID)" aria-expanded="false" aria-controls="collapseSum@(item.ID)">
                                            @(string.Join(" ", noteWords.Take(7)) + "...")
                                        </a>
                                        <div class="collapse" id="collapseSum@(item.ID)">
                                            <div class="well">
                                                @(string.Join(" ", noteWords.Skip(7)))
                                            </div>
                                        </div>
                                    }
                                    else
                                    {
                                        @item.Notes
                                    }
                                }
                                @*For help with Bootstrap Collapse see: https://getbootstrap.com/docs/3.3/javascript/#collapse*@
                            </td>
                            <td>
                                <a asp-controller="PatientAppt" asp-action="Update" asp-route-id="@item.ID">
                                    <span class="btn btn-sm btn-outline-primary">&#x270D;</span>
                                </a>
                                <a asp-controller="PatientAppt" asp-action="Remove" asp-route-id="@item.ID">
                                    <span class="btn btn-sm btn-outline-danger">&#x274C</span>
                                </a>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td></td>
                        <td align="right">
                            Total Fees:
                        </td>
                        <td>
                            <strong>@totalFees.ToString("c")</strong>
                        </td>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </div>
        </dd>
    </dl>
    <partial name="_PagingNavBar" />
</form>
<div>
    <a asp-action="Edit" asp-controller="Patients" asp-route-id="@patient.ID">Edit</a> |
    <a asp-action="Index" asp-controller="Patients">Back to Patient List</a>
</div>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="popover"]').popover();
        });
        //Helps PWA avoid prompting to resubmit data if user clicks "BACK" button and returns here.
        //if (window.history.replaceState) {
        //    window.history.replaceState(null, null, window.location.href);
        //}
    </script>
}

MedicalOffice/Views/PatientAppt/Remove.cshtml
@model MedicalOffice.Models.Appointment

@{
    ViewData["Title"] = "Remove Appointment";
}

<h2>Remove Appointment for Patient: @Model.Patient.FullName</h2>

<h3>Are you sure you want to delete this Appointment?</h3>
<div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.appDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.appDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Patient)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Patient.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.extraFee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.extraFee)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApptReason)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApptReason.ReasonName)
        </dd>
    </dl>

    <form asp-action="Remove">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-controller="PatientAppt" asp-route-PatientID="@Model.PatientID">Back to Patient</a>
    </form>
</div>

MedicalOffice/Views/PatientAppt/Update.cshtml
@model MedicalOffice.Models.Appointment

@{
    ViewData["Title"] = "Update Appointment";
}

<h2>Update Appointment for Patient:  @Model.Patient.FullName</h2>

<hr />
<form asp-action="Update">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" name="PatientID" value="@Model.PatientID" />
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="appDate" class="control-label"></label>
                    <input asp-for="appDate" class="form-control" />
                    <span asp-validation-for="appDate" class="text-danger"></span>
                </div>
                <label asp-for="Notes" class="control-label"></label>
                <textarea asp-for="Notes" rows="5" cols="40" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="extraFee" class="control-label"></label>
                <input asp-for="extraFee" class="form-control" />
                <span asp-validation-for="extraFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApptReasonID" class="control-label"></label>
                <select asp-for="ApptReasonID" class="form-control" asp-items="ViewBag.ApptReasonID">
                    <option value="">No Reason Given</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

        </div>
    </div>
</form>
<div>
    <a asp-action="Index" asp-controller="PatientAppt" asp-route-PatientID="@Model.PatientID">Back to Patient</a>
</div>