MedicalOffice/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicalOffice.Data;
using MedicalOffice.Models;
using MedicalOffice.ViewModels;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.AspNetCore.Authorization;
using MedicalOffice.Utilities;

namespace MedicalOffice.Controllers
{
    [Authorize(Roles ="Admin,Supervisor")]
    public class DoctorsController : Controller
    {
        private readonly MedicalOfficeContext _context;

        public DoctorsController(MedicalOfficeContext context)
        {
            _context = context;
        }

        // GET: Doctors
        public async Task<IActionResult> Index(int? page, int? pageSizeID)
        {
            var doctors = from d in _context.Doctors
                .Include(d => d.DoctorSpecialties).ThenInclude(d => d.Specialty)
                          select d;
            //Handle Paging
            int pageSize;//This is the value we will pass to PaginatedList
            if (pageSizeID.HasValue)
            {
                //Value selected from DDL so use and save it to Cookie
                pageSize = pageSizeID.GetValueOrDefault();
                CookieHelper.CookieSet(HttpContext, "pageSizeValue", pageSize.ToString(), 30);
            }
            else
            {
                //Not selected so see if it is in Cookie
                pageSize = Convert.ToInt32(HttpContext.Request.Cookies["pageSizeValue"]);
            }
            pageSize = (pageSize == 0) ? 2 : pageSize;//Neither Selected or in Cookie so go with default
            ViewData["pageSizeID"] =
                new SelectList(new[] { "2", "5", "10", "20", "30", "40", "50", "100", "500" }, pageSize.ToString());
            var pagedData = await PaginatedList<Doctor>.CreateAsync(doctors.AsNoTracking(), page ?? 1, pageSize);
            return View(pagedData);
        }

        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors.Include(d=>d.Patients)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            Doctor doctor = new Doctor();
            PopulateAssignedSpecialtyData(doctor);
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,MiddleName,LastName")] Doctor doctor, string[] selectedOptions)
        {
            try
            {
                UpdateDoctorSpecialties(selectedOptions, doctor);
                if (ModelState.IsValid)
                {
                    _context.Add(doctor);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Something went wrong in the database.");
            }
            PopulateAssignedSpecialtyData(doctor);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
               .Include(d => d.DoctorSpecialties).ThenInclude(d => d.Specialty)
               .AsNoTracking()
               .SingleOrDefaultAsync(d => d.ID == id);

            if (doctor == null)
            {
                return NotFound();
            }
            PopulateAssignedSpecialtyData(doctor);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string[] selectedOptions)
        {
            //Get the object from the database
            var doctorToUpdate = await _context.Doctors
                .Include(d => d.DoctorSpecialties).ThenInclude(d => d.Specialty)
                .SingleOrDefaultAsync(d => d.ID == id);
            if (doctorToUpdate==null)
            {
                return NotFound();
            }

            //Update the Doctor's Specialties
            UpdateDoctorSpecialties(selectedOptions, doctorToUpdate);


            //Try updating it wiht the posted values
            if (await TryUpdateModelAsync<Doctor>(doctorToUpdate, "",
                d=>d.FirstName, d => d.MiddleName, d => d.LastName))
            {
                try
                {
                    _context.Update(doctorToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctorToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Something went wrong in the database.");
                }
                return RedirectToAction(nameof(Index));
            }
            //Validaiton Error so give the user another chance.
            PopulateAssignedSpecialtyData(doctorToUpdate);
            return View(doctorToUpdate);
        }

        // GET: Doctors/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctor = await _context.Doctors.FindAsync(id);
            try
            {
                _context.Doctors.Remove(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException dex)
            {
                if (dex.InnerException.Message.Contains("FK_Patients_Doctors_DoctorID"))
                {
                    ModelState.AddModelError("", "Unable to save changes. Remember, you cannot delete a Doctor that has Patients.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(doctor);

        }

        public PartialViewResult ListOfSpecialtiesDetails(int id)
        {
            var query = from s in _context.DoctorSpecialties.Include(p => p.Specialty)
                        where s.DoctorID == id
                        select s;
            return PartialView("_ListOfSpecialities", query.ToList());
        }

        public PartialViewResult ListOfPatientsDetails(int id)
        {
            var query = from s in _context.Patients
                        where s.DoctorID == id
                        select s;
            return PartialView("_ListOfPatients", query.ToList());
        }
        public PartialViewResult DoctorPD(int id)
        {
            //Now get the MASTER record, the Doctor, so it can be displayed at the top of the screen
            Doctor doctor = _context.Doctors
                .Where(p => p.ID == id).FirstOrDefault();
            ViewBag.Doctor = doctor;
            var query = from d in _context.DoctorPhysicalDescriptions
                        where d.DoctorID == id
                        select d;
            return PartialView("_DoctorPhysicalDescription", query.FirstOrDefault());
        }
                
        private void PopulateAssignedSpecialtyData(Doctor doctor)
        {
            var allSpecialties = _context.Specialties;
            var docSpecialties = new HashSet<int>(doctor.DoctorSpecialties.Select(b => b.SpecialtyID));
            var selected = new List<OptionVM>();

MedicalOffice/Controllers/LookupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MedicalOffice.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MedicalOffice.Controllers
{
    public class LookupsController : Controller
    {
        private readonly MedicalOfficeContext _context;

        public LookupsController(MedicalOfficeContext context)
        {
            _context = context;
        }

        public IActionResult Index(string Tab)
        {
            ///Note: select the tab you want to load by passing in
            ///the ID of the tab such as MedicalTrialsTab, ConditionsTab
            ///or ApptReasonsTab
            ViewData["Tab"] = Tab;
            return View();
        }
        public PartialViewResult Conditions()
        {
            ViewData["ConditionsID"] = new SelectList(_context.Conditions.OrderBy(a => a.ConditionName), "ID", "ConditionName");
            return PartialView("_Conditions");
        }
        public PartialViewResult MedicalTrials()
        {
            ViewData["MedicalTrialsID"] = new SelectList(_context.MedicalTrials.OrderBy(a => a.TrialName), "ID", "TrialName");
            return PartialView("_MedicalTrials");
        }
        public PartialViewResult ApptReasons()
        {
            ViewData["ApptReasonsID"] = new SelectList(_context.ApptReasons.OrderBy(a => a.ReasonName), "ID", "ReasonName");
            return PartialView("_ApptReasons");
        }
    }
}

MedicalOffice/Views/Shared/_DoctorCreate.cshtml
@model MedicalOffice.Models.Doctor
<form asp-action="Create" asp-controller="Doctors" id="createDoctorForm">
    <div class="row">
        <div class="col-md-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" id="submitCreate" class="btn btn-outline-dark" />
            </div>
        </div>
    </div>
</form>

MedicalOffice/Views/Shared/_DoctorCreateModal.cshtml
<!-- Modal-->
<div class="modal fade" id="addDoctorModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Add New Doctor</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                @{ var d = new MedicalOffice.Models.Doctor();
                    <partial name="_DoctorCreate" model="d" />
                }
            </div>
        </div>
    </div>
</div>

MedicalOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Medical Office</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Medical Office</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="Index">Patients</a>
                        </li>
                         @if (User.IsInRole("Admin") || User.IsInRole("Supervisor"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Office Menu<b class="caret"></b>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Doctors" asp-action="Index">Doctors</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="MedicalTrials" asp-action="Index">Notify Trial Participants</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Lookups" asp-action="Index">Maintain Lookup Values</a>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Register User</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="Index">Manage Employees</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="UserRoles" asp-action="Index">Security Roles</a>
                                    }
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Medical Office - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

MedicalOffice/Views/Shared/_PageSizeModal.cshtml
<!-- Modal-->
<div class="modal fade" id="pageSizeModal" tabindex="-1" role="dialog" aria-labelledby="pageSizeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="pageSizeModalLabel">Set Page Size</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Page Size: </span>
                            </div>
                            @Html.DropDownList("pageSizeID", null, htmlAttributes: new { @class = "form-control" })
                            <div class="input-group-append">
                                <input type="submit" class="btn btn-primary" value="Set Page Size" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MedicalOffice/Views/Shared/_PagingNavBar.cshtml
<partial name="_PageSizeModal" />
@{
    if (Model.TotalPages == 1)
    {
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">
                <button type="button" title="Click to change page size." data-toggle="modal" data-target="#pageSizeModal" class="btn btn-primary">
                    Page @Model.PageIndex of @Model.TotalPages
                </button>
            </li>
        </ul>
    }
    else
    {
        var jumpAmount = (Model.TotalPages > 25) ? 10 : 5;
        var prevDisabled = !Model.HasPreviousPage ? "disabled='disabled'" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled='disabled'" : "";
        var stepBack = (Model.PageIndex <= jumpAmount) ? 1 : Model.PageIndex - jumpAmount;
        var stepForward = (Model.PageIndex + jumpAmount > Model.TotalPages) ? Model.TotalPages : Model.PageIndex + jumpAmount;
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">
                <button type="submit" name="page" value="1" @prevDisabled class="btn page-link">
                    <span aria-hidden="true">&lArr;</span>&nbsp;First
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" value="@(stepBack)" @prevDisabled
                        data-toggle="tooltip" title="Jump Back @(Model.PageIndex-stepBack) Pages" class="btn page-link">
                    <span aria-hidden="true">&lArr;</span>
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @prevDisabled value="@(Model.PageIndex - 1)" class="btn page-link">
                    <span aria-hidden="true">&larr;</span>&nbsp;Previous
                </button>
            </li>
            <li class="page-item">
                <button type="button" title="Click to change page size." data-toggle="modal" data-target="#pageSizeModal" class="btn btn-primary">
                    Page @Model.PageIndex of @Model.TotalPages
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @nextDisabled value="@(Model.PageIndex + 1)" class="btn page-link">
                    Next&nbsp;<span aria-hidden="true">&rarr;</span>
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @nextDisabled value="@(stepForward)" title="Jump Forward @(stepForward-Model.PageIndex) Pages" class="btn page-link">
                    <span aria-hidden="true">&rArr;</span>
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @nextDisabled value="@(Model.TotalPages)" class="btn page-link">
                    Last&nbsp;<span aria-hidden="true">&rArr;</span>
                </button>
            </li>
        </ul>
    }
}